version: '3'
services:
    db:
        image: mysql:5.7
        container_name: my-db
        ports:
            - "3308:3306"
        # environment:
        #     - MYSQL_ROOT_PASSWORD=12345678
        #     - SHOW=true
        env_file:
            - env.txt
        volumes:
            - /Users/cactus/SprintDO/Docker/docker-compose/mysql:/var/lib/mysql